USE MARCIN_NIERUCHOMOSC;

DROP TABLE NAJEM_INDYWIDUALNY;
DROP TABLE KLIENT_INDYWIDUALNY;
DROP TABLE RACHUNEK;
DROP TABLE NAJEM_FIRMA;
DROP TABLE KLIENT_FIRMA;
DROP TABLE FAKTURA;
DROP TABLE NIERUCHOMOSC;
DROP TABLE AGENT_NIERUCHOMOSCI;
DROP TABLE KATEGORIA_NIERUCHOMOSCI;
DROP TABLE NAJEM_STATUS;

DROP VIEW VIEW_GET_UUID;
DROP VIEW VIEW_LOKAL_UZYTKOWY_I_AGENT;
DROP VIEW VIEW_POWIERZCHNIA_BIUROWA_I_AGENT;
DROP VIEW VIEW_MIESZKANIA_I_AGENT;

DROP FUNCTION FN_ILE_PROCENT_RABATU;
DROP FUNCTION FN_POLICZ_BRUTTO;
DROP FUNCTION FN_POLICZ_NETTO;
DROP FUNCTION FN_POLICZ_RABAT;
DROP FUNCTION FN_SPRAWDZ_CZY_WYNAJEM_FRIMA_ISTNIEJE;
DROP FUNCTION FN_SPRAWDZ_CZY_WYNAJEM_INDYWIDUALNY_ISTNIEJE;
DROP FUNCTION getUUID;
DROP FUNCTION FN_ZWROC_TABELE_WYNAJEM_FIRMA_JOIN_FAKTURA_BY_NAJEM_ID;
DROP FUNCTION FN_ZWROC_TABELE_WYNAJEM_INDYWIDUALNY_JOIN_RACHUNEK_BY_NAJEM_ID;

DROP PROCEDURE  PROC_DODAJ_FAKTURA;
DROP PROCEDURE PROC_DODAJ_RACHUNEK;
DROP PROCEDURE PROC_NAJEM_FIRMA_UPDATE_STATUS_WYNAJMU_JAK_FAKTURA_OPLACONA;
DROP PROCEDURE PROC_NAJEM_INDYWIDUALNY_UPDATE_STATUS_WYNAJMU_JAK_FAKTURA_OPLACONA;
DROP PROCEDURE PROC_ZMIEN_STATUS_OPLACONY_NA_ARCHIWUM_FIRMA;
DROP PROCEDURE PROC_ZMIEN_STATUS_OPLACONY_NA_ARCHIWUM_INDYWIDUALNY;


DROP USER ADMIN_USER;
DROP USER AGENT_USER;
DROP USER KLIENT_USER;

DROP ROLE AGENT;
DROP ROLE KLIENT;

DROP LOGIN ADMIN_LOGIN;
DROP LOGIN AGENT_LOGIN;
DROP LOGIN KLIENT_LOGIN;




