USE MARCIN_NIERUCHOMOSC;

GO

ALTER TABLE NAJEM_INDYWIDUALNY
    ADD CONSTRAINT CHECK_IND_DATA_OD CHECK (DATA_OD >= GETDATE());

GO

ALTER TABLE NAJEM_FIRMA
    ADD CONSTRAINT CHECK_FIRMA_DATA_OD CHECK (DATA_OD >= GETDATE());

GO

ALTER TABLE KLIENT_INDYWIDUALNY
    ADD CONSTRAINT CHECK_PESEL CHECK (LEN(PESEL) = 11);

GO

ALTER TABLE KLIENT_FIRMA
    ADD CONSTRAINT CHECK_NIP CHECK (LEN(NIP) = 10);

GO

ALTER TABLE KLIENT_FIRMA
    ADD CONSTRAINT CHECK_FIRMA_KOD_POCZTOWY CHECK (LEN(KOD_POCZTOWY) = 6);

GO

ALTER TABLE KLIENT_INDYWIDUALNY
    ADD CONSTRAINT CHECK_IND_KOD_POCZTOWY CHECK (LEN(KOD_POCZTOWY) = 6);

GO

ALTER TABLE NIERUCHOMOSC
    ADD CONSTRAINT CHECK_NIERUCHOMOSC_KOD_POCZTOWY CHECK (LEN(KOD_POCZTOWY) = 6);

GO