USE MARCIN_NIERUCHOMOSC;

GO

-- WIDOK NIERUCHOMOSC W KATEGORII MIESZKANIE + SZCZEGÓLY AGENTA PRZYPISANEGO DO NIERUCHOMOSCI
CREATE VIEW VIEW_MIESZKANIA_I_AGENT AS
(
SELECT ID_NIERUCHOMOSC,
       AN.IMIE                        AS IMIE_AGENT,
       AN.NAZWISKO                    AS NAZWISKO_AGENT,
       AN.NUMER_TELEFONU,
       NIERUCHOMOSC.NAZWA             AS NIERUCHOMOSC,
       KN.NAZWA                       AS KATEGORIA,
       NIERUCHOMOSC.ADRES_ULICA_LOKAL AS ADRES,
       MIESCOWOSC,
       METRAZ,
       CENA_DOBA_NETTO
FROM NIERUCHOMOSC
         JOIN AGENT_NIERUCHOMOSCI AN on NIERUCHOMOSC.ID_AGENT = AN.ID_AGENT
         JOIN KATEGORIA_NIERUCHOMOSCI KN on NIERUCHOMOSC.RODZAJ = KN.ID_KATEGORIA
WHERE KN.NAZWA = 'MIESZKANIE'
    )

GO

SELECT *
FROM VIEW_MIESZKANIA_I_AGENT;

GO

-- WIDOK NIERUCHOMOSC W KATEGORII POWIERZCHNIA_BIUROWA + SZCZEGÓLY AGENTA PRZYPISANEGO DO NIERUCHOMOSCI
CREATE VIEW VIEW_POWIERZCHNIA_BIUROWA_I_AGENT AS
(
SELECT ID_NIERUCHOMOSC,
       AN.IMIE                        AS IMIE_AGENT,
       AN.NAZWISKO                    AS NAZWISKO_AGENT,
       AN.NUMER_TELEFONU,
       NIERUCHOMOSC.NAZWA             AS NIERUCHOMOSC,
       KN.NAZWA                       AS KATEGORIA,
       NIERUCHOMOSC.ADRES_ULICA_LOKAL AS ADRES,
       MIESCOWOSC,
       METRAZ,
       CENA_DOBA_NETTO
FROM NIERUCHOMOSC
         JOIN AGENT_NIERUCHOMOSCI AN on NIERUCHOMOSC.ID_AGENT = AN.ID_AGENT
         JOIN KATEGORIA_NIERUCHOMOSCI KN on NIERUCHOMOSC.RODZAJ = KN.ID_KATEGORIA
WHERE KN.NAZWA = 'POWIERZCHNIA_BIUROWA'
    )

GO

SELECT *
FROM VIEW_POWIERZCHNIA_BIUROWA_I_AGENT;

GO

-- WIDOK NIERUCHOMOSC W KATEGORII LOKAL_UZYTKOWY + SZCZEGÓLY AGENTA PRZYPISANEGO DO NIERUCHOMOSCI
CREATE VIEW VIEW_LOKAL_UZYTKOWY_I_AGENT AS
(
SELECT ID_NIERUCHOMOSC,
       AN.IMIE                        AS IMIE_AGENT,
       AN.NAZWISKO                    AS NAZWISKO_AGENT,
       AN.NUMER_TELEFONU,
       NIERUCHOMOSC.NAZWA             AS NIERUCHOMOSC,
       KN.NAZWA                       AS KATEGORIA,
       NIERUCHOMOSC.ADRES_ULICA_LOKAL AS ADRES,
       MIESCOWOSC,
       METRAZ,
       CENA_DOBA_NETTO
FROM NIERUCHOMOSC
         JOIN AGENT_NIERUCHOMOSCI AN on NIERUCHOMOSC.ID_AGENT = AN.ID_AGENT
         JOIN KATEGORIA_NIERUCHOMOSCI KN on NIERUCHOMOSC.RODZAJ = KN.ID_KATEGORIA
WHERE KN.NAZWA = 'LOKAL_UŻYTKOWY'
    )

GO

SELECT *
FROM VIEW_LOKAL_UZYTKOWY_I_AGENT;


-- WIDOK PRZYCHÓD ZA NAJEM INDYWIDUALNY W ROKU 2019 W ZALEZNOSCI OD KATEGORII NIERUCHOMOSCI

SELECT N.NAZWA, SUM(R2.CENA_NETTO)
FROM NAJEM_INDYWIDUALNY
         JOIN NIERUCHOMOSC N on NAJEM_INDYWIDUALNY.ID_NIERUCHOMOSC = N.ID_NIERUCHOMOSC
         JOIN RACHUNEK R2 on NAJEM_INDYWIDUALNY.ID_RACHUNEK = R2.ID_RACHUNEK
WHERE R2.CZY_OPLACONY=1
GROUP BY N.NAZWA;


