USE MARCIN_NIERUCHOMOSC;

GO

CREATE LOGIN ADMIN_LOGIN WITH PASSWORD = 'qaz123', CHECK_POLICY = OFF;
CREATE USER ADMIN_USER FOR LOGIN ADMIN_LOGIN;
EXEC sys.sp_addrolemember @membername = 'ADMIN_USER', @rolename = 'db_owner';

GO

CREATE LOGIN AGENT_LOGIN WITH PASSWORD = 'qaz123', CHECK_POLICY = OFF;
CREATE USER AGENT_USER FOR LOGIN AGENT_LOGIN;
CREATE ROLE AGENT;
GRANT SELECT ON NIERUCHOMOSC TO AGENT;
GRANT SELECT ON KLIENT_INDYWIDUALNY TO AGENT;
GRANT SELECT ON KLIENT_FIRMA TO AGENT;
GRANT INSERT ON NAJEM_INDYWIDUALNY TO AGENT;
GRANT SELECT ON NAJEM_FIRMA TO AGENT;

EXEC sys.sp_addrolemember @membername = 'AGENT_USER', @rolename = 'AGENT';

GO

CREATE ROLE KLIENT;
GRANT SELECT ON NIERUCHOMOSC TO KLIENT;
GRANT SELECT ON KATEGORIA_NIERUCHOMOSCI TO KLIENT;
GRANT SELECT ON AGENT_NIERUCHOMOSCI TO KLIENT;
GRANT SELECT ON RACHUNEK TO KLIENT;

DENY INSERT, ALTER, UPDATE , DELETE ON NIERUCHOMOSC TO KLIENT;
DENY INSERT, ALTER, UPDATE , DELETE ON KATEGORIA_NIERUCHOMOSCI TO KLIENT;
DENY INSERT, ALTER, UPDATE , DELETE ON AGENT_NIERUCHOMOSCI TO KLIENT;
DENY INSERT, ALTER, UPDATE , DELETE ON RACHUNEK TO KLIENT;

DENY SELECT, INSERT, ALTER , UPDATE , DELETE ON TO KLIENT;


GO



