USE MARCIN_NIERUCHOMOSC;

GO

CREATE LOGIN ADMIN_LOGIN WITH PASSWORD = 'qaz123', CHECK_POLICY = OFF;
CREATE USER ADMIN_USER FOR LOGIN ADMIN_LOGIN;
EXEC sys.sp_addrolemember @membername = 'ADMIN_USER', @rolename = 'db_owner';

GO

CREATE LOGIN AGENT_LOGIN WITH PASSWORD = 'qaz123', CHECK_POLICY = OFF;
CREATE USER AGENT_USER FOR LOGIN AGENT_LOGIN;
CREATE ROLE AGENT;
GRANT SELECT ON NIERUCHOMOSC TO AGENT;
GRANT SELECT ON KLIENT_INDYWIDUALNY TO AGENT;
GRANT SELECT ON KLIENT_FIRMA TO AGENT;
GRANT SELECT ON AGENT_NIERUCHOMOSCI TO AGENT;
GRANT INSERT ON NAJEM_INDYWIDUALNY TO AGENT;
GRANT SELECT ON NAJEM_FIRMA TO AGENT;
GRANT SELECT ON VIEW_LOKAL_UZYTKOWY_I_AGENT TO AGENT;
GRANT SELECT ON VIEW_MIESZKANIA_I_AGENT TO AGENT;
GRANT SELECT ON VIEW_POWIERZCHNIA_BIUROWA_I_AGENT TO AGENT;

EXEC sys.sp_addrolemember @membername = 'AGENT_USER', @rolename = 'AGENT';

GO

CREATE LOGIN KLIENT_LOGIN WITH PASSWORD = 'qaz123', CHECK_POLICY = OFF;
CREATE USER KLIENT_USER FOR LOGIN KLIENT_LOGIN;
CREATE ROLE KLIENT;
GRANT SELECT ON VIEW_MIESZKANIA_I_AGENT TO KLIENT;
GRANT SELECT ON VIEW_POWIERZCHNIA_BIUROWA_I_AGENT TO KLIENT;
GRANT SELECT ON VIEW_LOKAL_UZYTKOWY_I_AGENT TO KLIENT;

EXEC sys.sp_addrolemember @membername = 'KLIENT_USER', @rolename = 'KLIENT';


GO



